server:
  port: 8081
  servlet:
    context-path: /departments

application:
  description: @project.description@
  version: @project.version@

springdoc:
  show-actuator: false


pubsub:
  costcenter-subscription-id: costcenter-sub
  resource-subscription-id: resource-sub
  costcenter-resource-subscription-id: costcenter-resource-sub
  contract-subscription-id: contract-sub

spring:
  cloud:
    gcp:
      credentials:
        location: classpath:despesas-1616021701603-42ae4b39bb5b.json
      project-id: despesas-1616021701603
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: configserver:http://${CONFIG-SERVER}:8888
  datasource:
    # url: jdbc:h2:mem:mydb
    # jdbc:h2:file:~/h2/department
    url: jdbc:h2:file:~/h2/department
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect