server:
  port: 8081
  servlet:
    context-path: /sharing

application:
  description: @project.description@
  version: @project.version@

springdoc:
  show-actuator: false

# GCP Pub/Sub: All Configurations (Project ID and Subscriptions)
pubsub:
  costcenter-subscription-id: costcenter-sub
  resource-subscription-id: resource-sub
  costcenter-resource-subscription-id: costcenter-resource-sub
  contract-subscription-id: contract-sub

spring:
  # START: - Spring Cloud
  # Here we disable for now EUREKA (Service Discovery)
  # And we also disable the CONFIG SERVER
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
      # When config server is enabled, we need to uncomment this line below.
      # this will set where is the config server HOST.
      # import: configserver:http://${CONFIG-SERVER}:8888
  # START: - GCP Config (Google Cloud Platform)
    gcp:
      credentials:
        location: classpath:despesas-1616021701603-42ae4b39bb5b.json
      project-id: despesas-1616021701603
  # START: - JPA Data Base
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    # url: jdbc:h2:mem:sharing
    # jdbc:h2:file:~/h2/department
    url: jdbc:h2:file:~/h2/sharing
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect