server:
  port: 8081
  servlet:
    context-path: /departments

application:
  description: @project.description@
  version: @project.version@

springdoc:
  show-actuator: true

pubsub:
  topic-id: rateio
  subscription-id: costcenter

spring:
  cloud:
    gcp:
      credentials:
        location: classpath:despesas-1616021701603-42ae4b39bb5b.json
      project-id: despesas-1616021701603
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: configserver:http://${CONFIG-SERVER}:8888
  datasource:
    # url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:C:/data/sample
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect